/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user.profile;

import executable.Client;
import java.awt.Toolkit;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import server.actors.AbstractActor;
import server.actors.Group;
import server.actors.User;
import view.util.UserRenderer;

/**
 *
 * @author user
 */
public class AdminPanel extends JPanel {

    /**
     * Creates new form AdminPanel
     */
    private final Client client;
    private final AbstractActor actor;
    
    private DefaultListModel<User> userRequestModel;
    
    public AdminPanel(Client c, AbstractActor actor) {
        this.client = c;
        this.actor = actor;
        
        userRequestModel = new DefaultListModel<>();
        
        initComponents();
        listMembers(false);
    }

    private void listMembers(boolean reload){
        if(reload){
            userRequestModel.clear();
        }
        Iterator it = actor.getRequests().iterator();
        int i;
        for(i = 0; it.hasNext(); i++){
            userRequestModel.add(i, (User) it.next());
        }
        requestList.setCellRenderer(new UserRenderer());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newMembersRequest = new javax.swing.JLabel();
        blockedMembers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestList = new JList<>(userRequestModel);
        jScrollPane2 = new javax.swing.JScrollPane();
        blockedList = new javax.swing.JList<>();
        searchBox = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 153));
        setPreferredSize(new java.awt.Dimension(1086, 638));

        newMembersRequest.setText("Solicitações de Entrada");

        blockedMembers.setText("Membros Bloqueados");

        jScrollPane1.setViewportView(requestList);

        jScrollPane2.setViewportView(blockedList);

        searchBox.setText("jTextField1");

        SearchButton.setText("jButton1");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newMembersRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(blockedMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newMembersRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(blockedMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBox)
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        Group group = (Group) actor;
        String member = searchBox.getText().toLowerCase();
        if(member.equals(client.getUser().getId())){
            JOptionPane.showMessageDialog(client, "Você já é amigo de si mesmo (ou não!)", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else if(actor.isRelative(client.getDatabase().getFromMail(member))){
            Toolkit.getDefaultToolkit().beep();
            String[] options = {"Tornar Moderador", "Remover", "Bloquear", "Cancelar"};
            if(group.isAdmin(client.getDatabase().getFromMail(member))){
                options[0] = "Remover Moderador";
            }
            if(actor.isBlocked(client.getDatabase().getFromMail(member))){
                options[2] = "Desbloquear";
            }
            User user = client.getDatabase().getFromMail(member);
            int selection = JOptionPane.showOptionDialog(client, "O que deseja fazer com " + user.getName() + " ?" , "Opções de Interação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            switch(selection){
                case 0:
                  if(group.isAdmin(client.getDatabase().getFromMail(member))){
                      group.removeAdmin(user);
                  } else {
                      group.addAdmin(user);
                  }
                  break;
                case 1:
                    group.removeRelative(user);
                    JOptionPane.showMessageDialog(client, user.getName() + " foi removido!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 2:
                    if(actor.isBlocked(user)){
                        group.block(user);
                    } else{
                        group.unblock(user);
                    }
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchButton;
    private javax.swing.JList<String> blockedList;
    private javax.swing.JLabel blockedMembers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel newMembersRequest;
    private javax.swing.JList<User> requestList;
    private javax.swing.JTextField searchBox;
    // End of variables declaration//GEN-END:variables
}
