/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user.profile;

import executable.Client;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import server.Post;
import server.actors.User;
import util.Validator;
import view.user.post.NewPost;
import view.user.post.ViewPost;
import view.util.PostRenderer;

/**
 *
 * @author David
 */
public class Wall extends javax.swing.JPanel {

    private final Client client;
    private final User user;
    private final boolean isOwner;
    
    private DefaultListModel<Post> userPostModel;
    private DefaultListModel<Post> thirdUserPostModel;
    
    public Wall(Client c, User user) {
        client = c;
        this.user = user;
        isOwner = Validator.isSameEmail(client.getUser().getId(), user.getId());
        
        userPostModel = new DefaultListModel<>();
        thirdUserPostModel = new DefaultListModel<>();
        
        initComponents();
        listPosts(false);
    }

    public Wall(Client c){
        client = c;
        user = c.getUser();
        isOwner = Validator.isSameEmail(client.getUser().getId(), user.getId());
        
        userPostModel = new DefaultListModel<>();
        thirdUserPostModel = new DefaultListModel<>();
        
        initComponents();
    }
    
    public void listPosts(boolean reload){
        if(reload){
            userPostModel.clear();
            thirdUserPostModel.clear();
            postPanel.removeAll();
            postPanel.revalidate();
        }
        int i;
        Iterator it = user.getPosts().iterator();
        for(i = 0; it.hasNext(); i++){
            userPostModel.add(i,(Post) it.next());
        }
        wopList.setCellRenderer(new PostRenderer());
        it = user.getPostsFromOthers().iterator();
        for(i = 0; it.hasNext(); i++){
            thirdUserPostModel.add(i,(Post) it.next());
        }
        tpwpList.setCellRenderer(new PostRenderer());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wallOwnerPostsLabel = new javax.swing.JLabel();
        wopListPanel = new javax.swing.JScrollPane();
        wopList = new JList<>(userPostModel);
        thirdPersonWallPostLabel = new javax.swing.JLabel();
        tpwpListPanel = new javax.swing.JScrollPane();
        tpwpList = new JList<>(thirdUserPostModel);
        postPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 102, 153));

        wallOwnerPostsLabel.setText("<html>Mensagens de <b>" + user.getName() + "</b></html>");

        wopList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                wopListValueChanged(evt);
            }
        });
        wopListPanel.setViewportView(wopList);

        thirdPersonWallPostLabel.setText("Mensagens de Outros");

        tpwpListPanel.setViewportView(tpwpList);

        postPanel.add(new NewPost(client, user, this));
        postPanel.setLayout(new javax.swing.BoxLayout(postPanel, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wallOwnerPostsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wopListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tpwpListPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thirdPersonWallPostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wallOwnerPostsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wopListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thirdPersonWallPostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(356, 356, 356)
                                .addComponent(tpwpListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wopListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_wopListValueChanged
        int index = wopList.getSelectedIndex();
        if(index >= 0){
            Post selected = user.getPost(index);
            postPanel.removeAll();
            Iterator it = selected.getComments().iterator();
            while(it.hasNext()){
                postPanel.add(new ViewPost(client, this, (Post) it.next()));
            }
            postPanel.add(new ViewPost(client, this, selected));
            postPanel.revalidate();
        }
    }//GEN-LAST:event_wopListValueChanged

    public JPanel getPostPanel(){
        return postPanel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel postPanel;
    private javax.swing.JLabel thirdPersonWallPostLabel;
    private javax.swing.JList<Post> tpwpList;
    private javax.swing.JScrollPane tpwpListPanel;
    private javax.swing.JLabel wallOwnerPostsLabel;
    private javax.swing.JList<Post> wopList;
    private javax.swing.JScrollPane wopListPanel;
    // End of variables declaration//GEN-END:variables
}
