/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user;

import executable.Client;
import util.Constants;
import view.user.profile.Info;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import server.actors.User;
import util.Validator;
import view.user.profile.Wall;

/**
 *
 * @author David
 */
public class Profile extends JPanel {

    private final Client client;
    private final Home home;
    private final User user;
    
    private final boolean isOwner;
    
    public Profile(Client c, Home home) {
        this.client = c;
        this.home = home;
        this.user = c.getUser();
        isOwner = Validator.isSameEmail(user.getId(), client.getUser().getId());
        initComponents();
    }

    public Profile(Client c, User user, Home home) {
        this.client = c;
        this.user = user;
        this.home = home;
        isOwner = Validator.isSameEmail(user.getId(), client.getUser().getId());
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPhotoLabel = new javax.swing.JLabel();
        btUserName = new javax.swing.JButton();
        isFriendLabel = new javax.swing.JLabel();
        btUserInfo = new javax.swing.JButton();
        btUserWall = new javax.swing.JButton();
        btAddFriend = new javax.swing.JButton();
        page = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 102, 153));
        setPreferredSize(new java.awt.Dimension(1280, 660));

        userPhotoLabel.setIcon(new ImageIcon(user.getIcon().getImage().getScaledInstance(164, 164, Image.SCALE_SMOOTH)));
        userPhotoLabel.setOpaque(true);

        btUserName.setText("" + user.getName());
        btUserName.setToolTipText("" + user.getName());
        btUserName.setEnabled(false);

        btUserInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btUserInfo.setText("Perfil");
        btUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserInfoActionPerformed(evt);
            }
        });

        btUserWall.setText("Mural");
        btUserWall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserWallActionPerformed(evt);
            }
        });

        btAddFriend.setText("Adicionar Amigo");
        btAddFriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddFriendActionPerformed(evt);
            }
        });
        if(isOwner || client.getUser().isRelative(user)){
            btAddFriend.setVisible(false);
            btAddFriend.setEnabled(false);
        }

        page.setBackground(new java.awt.Color(0, 102, 153));
        page.setPreferredSize(new java.awt.Dimension(1086, 638));
        page.setLayout(new javax.swing.BoxLayout(page, javax.swing.BoxLayout.LINE_AXIS));
        page.removeAll();
        page.add(new Info(client, user, this));
        page.revalidate();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userPhotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isFriendLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUserWall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAddFriend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(page, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userPhotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isFriendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btUserWall, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAddFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        isFriendLabel.setHorizontalAlignment(SwingConstants.CENTER);
        if(!isOwner){
            if(client.getUser().isRelative(user)){
                isFriendLabel.setText("É seu amigo");
            }
        } else {
            isFriendLabel.setText("(Você)");
        }
    }// </editor-fold>//GEN-END:initComponents

    private void btUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserInfoActionPerformed
        btUserInfo.setFont(new java.awt.Font(Constants.FONT, 1, 11));
        btUserWall.setFont(new java.awt.Font(Constants.FONT, 0, 11));
        btUserWall.setText("Mural");
        page.removeAll();
        page.add(new Info(client, user, this));
        page.revalidate();
    }//GEN-LAST:event_btUserInfoActionPerformed

    private void btUserWallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserWallActionPerformed
        btUserWall.setFont(new java.awt.Font(Constants.FONT, 1, 11));
        btUserWall.setText("Nova Mensagem");
        btUserInfo.setFont(new java.awt.Font(Constants.FONT, 0, 11));
        page.removeAll();
        page.add(new Wall(client, user));
        page.revalidate();
    }//GEN-LAST:event_btUserWallActionPerformed

    private void btAddFriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddFriendActionPerformed
        User requester = client.getUser();
        if(user.isRequestSent(requester)){
            JOptionPane.showMessageDialog(client, "O pedido já foi enviado!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(user.isRelative(requester)){
            JOptionPane.showMessageDialog(client, user.getName() + " já é seu amigo!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else if(user.isBlocked(requester)){
            JOptionPane.showMessageDialog(client, "Você foi bloqueado por " + user.getName(), "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            user.newRequest(client.getUser());
            JOptionPane.showMessageDialog(client, "Pedido enviado para " + user.getName(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btAddFriendActionPerformed

    public void reloadUserPhoto(){
        userPhotoLabel.setIcon(new ImageIcon(user.getIcon().getImage().getScaledInstance(164, 164, Image.SCALE_SMOOTH)));
        home.getUserIcon().setIcon(new ImageIcon(client.getUser().getIcon().getImage().getScaledInstance(38, 38, Image.SCALE_SMOOTH)));
    }
    
    public JLabel getUserPhotoLabel(){
        return userPhotoLabel;
    }

    public Home getHome(){
        return home;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddFriend;
    private javax.swing.JButton btUserInfo;
    private javax.swing.JButton btUserName;
    private javax.swing.JButton btUserWall;
    private javax.swing.JLabel isFriendLabel;
    private javax.swing.JPanel page;
    private javax.swing.JLabel userPhotoLabel;
    // End of variables declaration//GEN-END:variables
}
