/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user;

import executable.Client;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import util.Constants;

/**
 *
 * @author David
 */
public class ViewGroups extends JPanel {

    private final Client client;
    private final Home home; 
    /**
     * Creates new form Groups
     */
    public ViewGroups(Client c, Home home) {
        this.client = c;
        this.home = home;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        groupList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        allGroupsList = new javax.swing.JList<>();
        searchGroup = new javax.swing.JTextField();
        searchBox = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createGroup = new javax.swing.JTextField();
        create = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 102));

        groupList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(groupList);

        allGroupsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(allGroupsList);

        searchGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchGroupMouseClicked(evt);
            }
        });
        searchGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGroupActionPerformed(evt);
            }
        });

        searchBox.setText("Pesquisar");
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("<Código do Usuário>");

        jLabel2.setText("<Código do Usuário>");

        createGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createGroupMouseClicked(evt);
            }
        });
        createGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupActionPerformed(evt);
            }
        });

        create.setText("Criar Grupo");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        searchGroup.setText(Constants.DEFAULT_SEARCH_MESSAGE);
        searchGroup.setText(Constants.DEFAULT_SEARCH_MESSAGE);
    }// </editor-fold>//GEN-END:initComponents

    private void searchGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchGroupMouseClicked
        if(searchGroup.getText().equals(Constants.DEFAULT_SEARCH_MESSAGE)){
            searchBox.setText("");
        }
    }//GEN-LAST:event_searchGroupMouseClicked

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        Toolkit.getDefaultToolkit().beep();
        String grupo = searchBox.getText().toLowerCase();
        if(grupo.equals(client.getDatabase().allGroups(grupo))){
            //se é membro
            if(client.getDatabase().getFromGroupId(grupo).isRelative(client.getUser())){
                String[] options = {"Sair do grupo", "Cancelar"};
            }
            //se não é
            else{
                String[] options = {"Solicitar entrada", "Cancelar"};
            }
        } else {
            JOptionPane.showMessageDialog(client, "Não existe nenhum grupo com esse nome!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_searchBoxActionPerformed

    private void createGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createGroupMouseClicked
        if(createGroup.getText().equals(Constants.DEFAULT_SEARCH_MESSAGE)){
            create.setText("");
        }
    }//GEN-LAST:event_createGroupMouseClicked

    private void createGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupActionPerformed
        
    }//GEN-LAST:event_createGroupActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        Toolkit.getDefaultToolkit().beep();
        String grupoCreate = create.getText().toLowerCase();
        if(client.getDatabase().allGroups(grupoCreate)){//the id is in use
            JOptionPane.showMessageDialog(client, "O grupo já existe com este ID!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            String name = JOptionPane.showInputDialog(client, "Insira o nome do Grupo: ", "Criar um Grupo", JOptionPane.QUESTION_MESSAGE);
            if(name.trim().equals("")){
                JOptionPane.showMessageDialog(client, "Nome Inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                //creates a new group
            }
        }
    }//GEN-LAST:event_createActionPerformed

    private void searchGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchGroupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> allGroupsList;
    private javax.swing.JButton create;
    private javax.swing.JTextField createGroup;
    private javax.swing.JList<String> groupList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchBox;
    private javax.swing.JTextField searchGroup;
    // End of variables declaration//GEN-END:variables
}
