/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user.post;

import executable.Client;
import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import server.Comment;
import server.Post;
import util.Constants;

/**
 *
 * @author David
 */
public class NewComment extends JPanel {
    
    private final Client client;
    private final Post post;

    private String selected_file;
    
    /**
     * Creates new form NewComment
     * @param c
     * @param post
     */
    public NewComment(Client c, Post post) {
        client = c;
        this.post = post;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPane = new javax.swing.JScrollPane();
        textField = new javax.swing.JTextArea();
        btAddPhoto = new javax.swing.JButton();
        selectedFileLabel = new javax.swing.JLabel();
        btSend = new javax.swing.JButton();

        textField.setColumns(20);
        textField.setRows(5);
        textPane.setViewportView(textField);

        btAddPhoto.setText("Adicionar Foto");
        btAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPhotoActionPerformed(evt);
            }
        });

        selectedFileLabel.setText(Constants.DEFAULT_FILE_TEXT);

        btSend.setText("Enviar");
        btSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectedFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAddPhoto)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textPane, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPhotoActionPerformed
        final JFileChooser fc = new JFileChooser();
        FileFilter imageFilter = new FileNameExtensionFilter("Arquivos de Imagem", ImageIO.getReaderFileSuffixes());
        fc.setFileFilter(imageFilter);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            selected_file = fc.getSelectedFile().getAbsolutePath();
            if(!selected_file.endsWith(".png") && !selected_file.endsWith(".jpg")){
                selected_file = "Inválido";
            }
            ImageIcon preview = new ImageIcon(selected_file);
            selectedFileLabel.setIcon(new ImageIcon(preview.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH)));
            selectedFileLabel.setText("Arquivo Selecionado: " + selected_file);
        }
    }//GEN-LAST:event_btAddPhotoActionPerformed

    private void btSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSendActionPerformed
        if(textField.getText().trim().equals("")){
            JOptionPane.showMessageDialog(client, "O texto está vazio!", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            if(selected_file.equals("Inválido") || selected_file.trim().equals("")){
                post.addComment(new Comment(textField.getText(), client.getUser()));
            } else {
                post.addComment(new Comment(textField.getText(), client.getUser(), selected_file));
            }
            JOptionPane.showMessageDialog(client, "Comentário Enviado!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddPhoto;
    private javax.swing.JButton btSend;
    private javax.swing.JLabel selectedFileLabel;
    private javax.swing.JTextArea textField;
    private javax.swing.JScrollPane textPane;
    // End of variables declaration//GEN-END:variables
}
